global using AventStack.ExtentReports;
global using Chubb.Studio.TestAutomationUtils.TestUtil;
global using Chubb.Studio.TestAutomationUtils.Extensions;
global using Newtonsoft.Json;
global using Chubb.CXP.Utils.Comparers;
global using Chubb.CXP.Utils.Json;
global using ExcelDataReader;
global using Newtonsoft.Json.Linq;
global using OpenQA.Selenium;
global using RestSharp;
global using RestSharp.Authenticators;
global using RestSharp.Extensions;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Configuration;
global using System.Data;
global using System.Drawing;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Xml;
global using static Chubb.CXP.Utils.Comparers.ComparisonResult;
global using _Excel = Microsoft.Office.Interop.Excel;
global using LogEntry = OpenQA.Selenium.LogEntry;
